server {
  listen 443 ssl;
  server_name auto.orbeone.com.br;

  client_max_body_size 25M;

  ssl_certificate /etc/nginx/certs/auto.orbeone.com.br/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/auto.orbeone.com.br/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    proxy_pass http://orbeauto-gateway;
    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options SAMEORIGIN always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
}
